### PR TITLE
Update language-basics.md

### PR DESCRIPTION
**Pull request by b0kch0y**
Thought this was the most appropriate place to put this since "built-in functions" were talked about on this page.

### CODE REVIEW

**Comment by trendzetter** [comment]
Whoa! Very nice addition

**Comment by trendzetter** [comment]
I must add that it probably deserves a better location to do this addition. Such as the official pact reference on readthedocs. Or a separate page. It's certainly not "basics".

**Comment by Randynamic** [comment]
Agree with @trendzetter here. IMHO, we should move it to the intermediate tab or create a new tab, 'build-in functions', where we explain built-in functions for the time being until we release developer.kadena.io.

**Comment by b0kch0y** [comment]
Ok, believe I added a tab under intermediate and a new file with the SPV info

**Comment by Randynamic** [comment]
close because of new PR https://github.com/kadena-community/docs/pull/51

**Pull request closed without merging**
