### PR TITLE
Update get-started.md

### PR DESCRIPTION
**Pull request by Tamil-dev**

### CODE REVIEW

**Comment by trendzetter** [comment]
seems spam

**Comment by Tamil-dev** [comment]
> 
hi shopper-auth.instacart.com
shoppers.instacart.com
www.instacart.com
krogerconvenience.instacart.com
beta.instacart.com
ads.instacart.com
api.instacart.com
connect.instacart.com
locations-api.instacart.com
enterprise-status.instacart.com
assets.instacart.com
admin.instacart.com
shopper-api.instacart.com
bashas.instacart.com
affiliate.instacart.com
smithsconvenience.instacart.com
mgs.instacart.com
kingsoopersconvenience.instacart.com
secure.instacart.com
food4lessconvenience.instacart.com
dillonsconvenience.instacart.com
shoppers-assets.instacart.com
display.instacart.com
shoppers-admin.instacart.com
shoppers-edge.instacart.com
frysconvenience.instacart.com
docs.instacart.com
qfcconvenience.instacart.com
foodway.instacart.com
heinens.instacart.com
sftp-admin-payments.instacart.com
keyfood.instacart.com
metromarketconvenience.instacart.com
metropolitan-market.instacart.com
login.instacart.com
tech.instacart.com
edge4.instacart.com
samsclub.instacart.com
news.instacart.com
pricechopperny.instacart.com
foodcity.instacart.com
naturalgrocers.instacart.com
api-catalog.instacart.com
retailer-platform-mesh.instacart.com
corporate.instacart.com
jewelosco.instacart.com
sunsetfoods.instacart.com
ralphsconvenience.instacart.com
email.instacart.com
connect-ian.instacart.com
covidresponse.instacart.com
widgets.instacart.com
joerandazzos.instacart.com
bug-bounty-guide.instacart.com
dashboard.instacart.com
citymarketconvenience.instacart.com
foodscoconvenience.instacart.com
ads-blog.instacart.com
fredmeyerconvenience.instacart.com
shopthepig.instacart.com
foodtown.instacart.com
paylessconvenience.instacart.com
cub.instacart.com
content2.instacart.com
wegmans-onecart.instacart.com
ajsfinefoods.instacart.com
t.instacart.com
superiorgrocers.instacart.com
stopandshop.instacart.com
marianosconvenience.instacart.com
shoppers-admin-edge.instacart.com
homeland.instacart.com
wildbynature.instacart.com
lamichoacanameatmarket.instacart.com
developers.instacart.com
order-sameday.instacart.com
food-4-less-kroger.instacart.com
ex.instacart.com
pricechopper.instacart.com
retailers.instacart.com
dashboard-api.instacart.com
logistics.instacart.com
myfoodcity.instacart.com
pbi.instacart.com
fr.instacart.com
pbis.instacart.com
flowers.instacart.com
amundsen.instacart.com
topsmarkets.instacart.com
schnucks-new.instacart.com
pbi-stg.instacart.com
beta-shopper-auth.instacart.com
albertsons-new.instacart.com
fooduniverse.instacart.com
food-lion.instacart.com
data-ingestion.instacart.com
cosentinosmarket.instacart.com
connect-docs.instacart.com
gfs.instacart.com
harrisonmarket.instacart.com

**Comment by Tamil-dev** [comment]
hey dude whats you thinking about that it's a bug @trendzetter

**Comment by trendzetter** [comment]
There is no bug. You proposed to change the link from the homepage to bing, which is wrong

**Pull request closed without merging**
